// Generated by CoffeeScript 1.6.3
var app, express, rootPath;

express = require('express');

app = express();

rootPath = process.cwd();

app.set('view engine', 'jade');

app.set('views', rootPath + '\\static\\views');

app.use('/static', express["static"](__dirname + '\\static'));

app.engine('jade', require('jade').__express);

app.get('/', function(req, res) {
  return res.render('index', {
    foo: 'bar'
  });
});

app.listen(8888, function() {
  return console.log('app start');
});
